name: keychain_access
description: "Flutter plugin to access Keychain Access apis on MacOS and iOS. 
  Provides a secure way to store and retrieve secure content from the keychain"
version: 1.0.4
homepage: https://github.com/leogps/keychain_access
documentation: https://github.com/leogps/keychain_access

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: KeychainAccessPlugin
      ios:
        pluginClass: KeychainAccessPlugin

platforms:
  macos:
  ios:

topics:
  - security
  - password
  - keychain
  - macos
  - apple